import type {
  GraphSnapshot,
  GraphThemeOverrides,
} from "@invariantcontinuum/graph/react";

// An atlas of graphs. Each preset is a distinct domain rendered by the same
// WASM engine — proof that node/edge types are plain strings, not a fixed
// taxonomy baked into the library. Every preset ships its own snapshot plus
// a theme override palette that feels native to its subject.

export interface Preset {
  readonly slug: string;
  readonly folio: string; // "I", "II", "III" — atlas page numbers
  readonly title: string;
  readonly subtitle: string;
  readonly essay: string; // short blurb shown under the title
  readonly snapshot: GraphSnapshot;
  readonly overrides: GraphThemeOverrides;
}

// Helper: a snapshot constructor that synthesizes meta.
type RawNode = Omit<GraphSnapshot["nodes"][number], "meta"> & {
  meta?: Record<string, unknown>;
};
type RawEdge = Omit<GraphSnapshot["edges"][number], "id" | "label" | "weight"> & {
  id?: string;
  label?: string;
  weight?: number;
};

function snap(nodes: RawNode[], edges: RawEdge[]): GraphSnapshot {
  return {
    nodes: nodes.map((n) => ({ ...n, meta: n.meta ?? {} })),
    edges: edges.map((e, i) => ({
      ...e,
      id: e.id ?? `e${i + 1}`,
      label: e.label ?? "",
      weight: e.weight ?? 1,
    })),
    meta: {
      node_count: nodes.length,
      edge_count: edges.length,
      last_updated: "2026-04-24T00:00:00Z",
    },
  };
}

// ── I. Microservice architecture ─────────────────────────────────────────
const architecture: Preset = {
  slug: "architecture",
  folio: "I",
  title: "Archipelago",
  subtitle: "A microservice architecture",
  essay:
    "Where the library began: services, databases, caches, and the quiet obligations between them. Nodes shown as civic blocks; broken policies glow.",
  snapshot: snap(
    [
      { id: "gw", name: "API Gateway", type: "service", domain: "edge", status: "healthy" },
      { id: "auth", name: "Auth", type: "service", domain: "identity", status: "healthy" },
      { id: "orders", name: "Orders", type: "service", domain: "commerce", status: "healthy" },
      { id: "inventory", name: "Inventory", type: "service", domain: "commerce", status: "healthy" },
      { id: "ship", name: "Shipping", type: "service", domain: "commerce", status: "warning" },
      { id: "notify", name: "Notifier", type: "service", domain: "ops", status: "healthy" },
      { id: "udb", name: "Users", type: "database", domain: "storage", status: "healthy" },
      { id: "odb", name: "Orders DB", type: "database", domain: "storage", status: "healthy" },
      { id: "cache", name: "Session", type: "cache", domain: "storage", status: "healthy" },
      { id: "stripe", name: "Stripe", type: "external", domain: "payments", status: "healthy" },
      { id: "s3", name: "Object Store", type: "external", domain: "storage", status: "healthy" },
      { id: "pol", name: "PII-redaction", type: "policy", domain: "security", status: "violation" },
    ],
    [
      { source: "gw", target: "auth", type: "depends" },
      { source: "gw", target: "orders", type: "depends" },
      { source: "auth", target: "udb", type: "reads" },
      { source: "orders", target: "odb", type: "writes" },
      { source: "orders", target: "inventory", type: "depends" },
      { source: "orders", target: "ship", type: "depends" },
      { source: "orders", target: "stripe", type: "depends" },
      { source: "ship", target: "notify", type: "emits" },
      { source: "auth", target: "cache", type: "reads" },
      { source: "inventory", target: "s3", type: "reads" },
      { source: "orders", target: "pol", type: "violates" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      service: {
        shape: "roundrectangle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        borderWidth: 1.3,
        halfWidth: 62,
        halfHeight: 22,
        labelColor: "#1A1714",
        labelFont: "Fraunces, serif",
        labelWeight: 500,
        labelSize: 12,
      },
      database: {
        shape: "barrel",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 48,
        halfHeight: 30,
        labelColor: "#1A1714",
        labelFont: "Fraunces, serif",
        labelSize: 11,
      },
      cache: {
        shape: "hexagon",
        color: "#F3EFE3",
        borderColor: "#8A7E68",
        halfWidth: 40,
        halfHeight: 26,
        labelFont: "Fraunces, serif",
      },
      external: {
        shape: "octagon",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 46,
        halfHeight: 26,
        labelFont: "Fraunces, serif",
      },
      policy: {
        shape: "diamond",
        color: "#F3EFE3",
        borderColor: "#7A2C1F",
        borderWidth: 2,
        halfWidth: 52,
        halfHeight: 32,
        labelColor: "#7A2C1F",
        labelFont: "Fraunces, serif",
      },
    },
    edgeTypes: {
      depends: { color: "#8A7E68", width: 1.2, style: "solid" },
      reads: { color: "#8A7E68", width: 1, style: "dashed" },
      writes: { color: "#1A1714", width: 1.4 },
      emits: { color: "#8A7E68", width: 1, style: "dotted" },
      violates: { color: "#7A2C1F", width: 2.2, style: "dashed" },
    },
  },
};

// ── II. Greek mythology ───────────────────────────────────────────────────
const mythology: Preset = {
  slug: "mythology",
  folio: "II",
  title: "Pantheon",
  subtitle: "Greek mythology, by lineage",
  essay:
    "Three generations of divinity. Titans, Olympians, the underworld — and the marriages, betrayals, and overthrows that bind them into a single tangled graph.",
  snapshot: snap(
    [
      { id: "chaos", name: "Chaos", type: "primordial", domain: "origin", status: "eternal" },
      { id: "gaia", name: "Gaia", type: "primordial", domain: "origin", status: "eternal" },
      { id: "uranus", name: "Uranus", type: "primordial", domain: "origin", status: "overthrown" },
      { id: "cronus", name: "Cronus", type: "titan", domain: "titan", status: "overthrown" },
      { id: "rhea", name: "Rhea", type: "titan", domain: "titan", status: "eternal" },
      { id: "zeus", name: "Zeus", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "hera", name: "Hera", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "poseidon", name: "Poseidon", type: "olympian", domain: "sea", status: "eternal" },
      { id: "hades", name: "Hades", type: "olympian", domain: "underworld", status: "eternal" },
      { id: "demeter", name: "Demeter", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "athena", name: "Athena", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "apollo", name: "Apollo", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "artemis", name: "Artemis", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "ares", name: "Ares", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "aphrodite", name: "Aphrodite", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "hermes", name: "Hermes", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "dionysus", name: "Dionysus", type: "olympian", domain: "olympus", status: "eternal" },
      { id: "persephone", name: "Persephone", type: "olympian", domain: "underworld", status: "eternal" },
      { id: "heracles", name: "Heracles", type: "mortal", domain: "mortal", status: "mortal" },
      { id: "prometheus", name: "Prometheus", type: "titan", domain: "titan", status: "exiled" },
    ],
    [
      { source: "chaos", target: "gaia", type: "begat" },
      { source: "gaia", target: "uranus", type: "begat" },
      { source: "uranus", target: "cronus", type: "begat" },
      { source: "gaia", target: "cronus", type: "begat" },
      { source: "cronus", target: "rhea", type: "wed" },
      { source: "cronus", target: "zeus", type: "begat" },
      { source: "rhea", target: "zeus", type: "begat" },
      { source: "cronus", target: "hera", type: "begat" },
      { source: "cronus", target: "poseidon", type: "begat" },
      { source: "cronus", target: "hades", type: "begat" },
      { source: "cronus", target: "demeter", type: "begat" },
      { source: "zeus", target: "hera", type: "wed" },
      { source: "zeus", target: "cronus", type: "overthrew" },
      { source: "zeus", target: "athena", type: "begat" },
      { source: "zeus", target: "apollo", type: "begat" },
      { source: "zeus", target: "artemis", type: "begat" },
      { source: "zeus", target: "ares", type: "begat" },
      { source: "zeus", target: "hermes", type: "begat" },
      { source: "zeus", target: "dionysus", type: "begat" },
      { source: "zeus", target: "aphrodite", type: "begat" },
      { source: "hera", target: "ares", type: "begat" },
      { source: "demeter", target: "persephone", type: "begat" },
      { source: "hades", target: "persephone", type: "wed" },
      { source: "zeus", target: "heracles", type: "begat" },
      { source: "prometheus", target: "zeus", type: "defied" },
      { source: "cronus", target: "uranus", type: "overthrew" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      primordial: {
        shape: "diamond",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        borderWidth: 2.4,
        halfWidth: 52,
        halfHeight: 36,
        labelFont: "Fraunces, serif",
        labelWeight: 700,
      },
      titan: {
        shape: "octagon",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 52,
        halfHeight: 32,
        labelFont: "Fraunces, serif",
      },
      olympian: {
        shape: "circle",
        color: "#F3EFE3",
        borderColor: "#7A2C1F",
        borderWidth: 1.6,
        halfWidth: 36,
        halfHeight: 36,
        labelColor: "#7A2C1F",
        labelFont: "Fraunces, serif",
        labelSize: 11,
      },
      mortal: {
        shape: "triangle",
        color: "#F3EFE3",
        borderColor: "#8A7E68",
        halfWidth: 36,
        halfHeight: 32,
        labelFont: "Fraunces, serif",
      },
    },
    edgeTypes: {
      begat: { color: "#1A1714", width: 1.1, style: "solid" },
      wed: { color: "#7A2C1F", width: 1.8, style: "solid" },
      overthrew: { color: "#7A2C1F", width: 2.2, style: "dashed" },
      defied: { color: "#8A7E68", width: 1.2, style: "dotted" },
    },
  },
};

// ── III. Molecules ────────────────────────────────────────────────────────
const molecules: Preset = {
  slug: "molecules",
  folio: "III",
  title: "Compounds",
  subtitle: "Three molecules, one notation",
  essay:
    "Water, methane, ethanol. Atoms are nodes; covalent bonds are edges. Same engine — now rendering structural formulae instead of service dependencies.",
  snapshot: snap(
    [
      // Water: H–O–H
      { id: "w_o", name: "O", type: "oxygen", domain: "water", status: "free" },
      { id: "w_h1", name: "H", type: "hydrogen", domain: "water", status: "free" },
      { id: "w_h2", name: "H", type: "hydrogen", domain: "water", status: "free" },
      // Methane: CH4
      { id: "m_c", name: "C", type: "carbon", domain: "methane", status: "free" },
      { id: "m_h1", name: "H", type: "hydrogen", domain: "methane", status: "free" },
      { id: "m_h2", name: "H", type: "hydrogen", domain: "methane", status: "free" },
      { id: "m_h3", name: "H", type: "hydrogen", domain: "methane", status: "free" },
      { id: "m_h4", name: "H", type: "hydrogen", domain: "methane", status: "free" },
      // Ethanol: CH3–CH2–OH
      { id: "e_c1", name: "C", type: "carbon", domain: "ethanol", status: "free" },
      { id: "e_c2", name: "C", type: "carbon", domain: "ethanol", status: "free" },
      { id: "e_o", name: "O", type: "oxygen", domain: "ethanol", status: "free" },
      { id: "e_h1", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
      { id: "e_h2", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
      { id: "e_h3", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
      { id: "e_h4", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
      { id: "e_h5", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
      { id: "e_h6", name: "H", type: "hydrogen", domain: "ethanol", status: "free" },
    ],
    [
      { source: "w_o", target: "w_h1", type: "single" },
      { source: "w_o", target: "w_h2", type: "single" },
      { source: "m_c", target: "m_h1", type: "single" },
      { source: "m_c", target: "m_h2", type: "single" },
      { source: "m_c", target: "m_h3", type: "single" },
      { source: "m_c", target: "m_h4", type: "single" },
      { source: "e_c1", target: "e_c2", type: "single" },
      { source: "e_c2", target: "e_o", type: "single" },
      { source: "e_o", target: "e_h6", type: "single" },
      { source: "e_c1", target: "e_h1", type: "single" },
      { source: "e_c1", target: "e_h2", type: "single" },
      { source: "e_c1", target: "e_h3", type: "single" },
      { source: "e_c2", target: "e_h4", type: "single" },
      { source: "e_c2", target: "e_h5", type: "single" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      oxygen: {
        shape: "circle",
        color: "#7A2C1F",
        borderColor: "#1A1714",
        borderWidth: 1.4,
        halfWidth: 22,
        halfHeight: 22,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
        labelWeight: 700,
        labelSize: 13,
      },
      hydrogen: {
        shape: "circle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        borderWidth: 1.2,
        halfWidth: 18,
        halfHeight: 18,
        labelColor: "#1A1714",
        labelFont: "Fraunces, serif",
        labelWeight: 700,
        labelSize: 12,
      },
      carbon: {
        shape: "circle",
        color: "#1A1714",
        borderColor: "#1A1714",
        halfWidth: 24,
        halfHeight: 24,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
        labelWeight: 700,
        labelSize: 13,
      },
    },
    edgeTypes: {
      single: { color: "#1A1714", width: 1.6, style: "solid" },
      double: { color: "#1A1714", width: 2.6, style: "solid" },
    },
  },
};

// ── IV. Hamlet ────────────────────────────────────────────────────────────
const hamlet: Preset = {
  slug: "hamlet",
  folio: "IV",
  title: "Elsinore",
  subtitle: "Hamlet's dramatis personae",
  essay:
    "Shakespeare's court reduced to a graph: who loves whom, who advises whom, who kills whom. The directed edges do almost all of the plot summary for you.",
  snapshot: snap(
    [
      { id: "hamlet", name: "Hamlet", type: "protagonist", domain: "denmark", status: "deceased" },
      { id: "claudius", name: "Claudius", type: "antagonist", domain: "denmark", status: "deceased" },
      { id: "gertrude", name: "Gertrude", type: "supporting", domain: "denmark", status: "deceased" },
      { id: "ophelia", name: "Ophelia", type: "supporting", domain: "denmark", status: "deceased" },
      { id: "polonius", name: "Polonius", type: "supporting", domain: "denmark", status: "deceased" },
      { id: "laertes", name: "Laertes", type: "foil", domain: "denmark", status: "deceased" },
      { id: "horatio", name: "Horatio", type: "supporting", domain: "denmark", status: "living" },
      { id: "ghost", name: "King Hamlet", type: "apparition", domain: "spectral", status: "deceased" },
      { id: "fortinbras", name: "Fortinbras", type: "foil", domain: "norway", status: "living" },
      { id: "rosencrantz", name: "Rosencrantz", type: "supporting", domain: "denmark", status: "deceased" },
      { id: "guildenstern", name: "Guildenstern", type: "supporting", domain: "denmark", status: "deceased" },
    ],
    [
      { source: "ghost", target: "hamlet", type: "haunts" },
      { source: "claudius", target: "ghost", type: "murdered" },
      { source: "claudius", target: "gertrude", type: "wed" },
      { source: "gertrude", target: "hamlet", type: "mothers" },
      { source: "hamlet", target: "ophelia", type: "loves" },
      { source: "polonius", target: "ophelia", type: "fathers" },
      { source: "polonius", target: "laertes", type: "fathers" },
      { source: "hamlet", target: "polonius", type: "kills" },
      { source: "laertes", target: "hamlet", type: "kills" },
      { source: "hamlet", target: "laertes", type: "kills" },
      { source: "hamlet", target: "claudius", type: "kills" },
      { source: "claudius", target: "gertrude", type: "kills" },
      { source: "horatio", target: "hamlet", type: "befriends" },
      { source: "rosencrantz", target: "hamlet", type: "betrays" },
      { source: "guildenstern", target: "hamlet", type: "betrays" },
      { source: "hamlet", target: "rosencrantz", type: "kills" },
      { source: "hamlet", target: "guildenstern", type: "kills" },
      { source: "ophelia", target: "polonius", type: "mourns" },
      { source: "fortinbras", target: "hamlet", type: "succeeds" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      protagonist: {
        shape: "roundrectangle",
        color: "#1A1714",
        borderColor: "#1A1714",
        halfWidth: 58,
        halfHeight: 26,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
        labelWeight: 600,
      },
      antagonist: {
        shape: "roundrectangle",
        color: "#7A2C1F",
        borderColor: "#7A2C1F",
        halfWidth: 58,
        halfHeight: 26,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
      },
      supporting: {
        shape: "roundrectangle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 56,
        halfHeight: 22,
        labelColor: "#1A1714",
        labelFont: "Fraunces, serif",
      },
      foil: {
        shape: "hexagon",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 50,
        halfHeight: 28,
        labelFont: "Fraunces, serif",
      },
      apparition: {
        shape: "diamond",
        color: "#F3EFE3",
        borderColor: "#8A7E68",
        borderWidth: 1,
        halfWidth: 58,
        halfHeight: 28,
        labelColor: "#8A7E68",
        labelFont: "Fraunces, serif",
      },
    },
    edgeTypes: {
      loves: { color: "#7A2C1F", width: 1.6 },
      kills: { color: "#1A1714", width: 2.2, style: "solid" },
      murdered: { color: "#1A1714", width: 2.2, style: "dashed" },
      betrays: { color: "#8A7E68", width: 1.4, style: "dashed" },
      haunts: { color: "#8A7E68", width: 1.2, style: "dotted" },
      wed: { color: "#7A2C1F", width: 1.6 },
      fathers: { color: "#1A1714", width: 1, style: "solid" },
      mothers: { color: "#1A1714", width: 1, style: "solid" },
      befriends: { color: "#1A1714", width: 1, style: "solid" },
      mourns: { color: "#8A7E68", width: 1, style: "dotted" },
      succeeds: { color: "#1A1714", width: 1.4, style: "dashed" },
    },
  },
};

// ── V. Philosophy ─────────────────────────────────────────────────────────
const philosophy: Preset = {
  slug: "philosophy",
  folio: "V",
  title: "Academy",
  subtitle: "Twenty-three centuries of influence",
  essay:
    "From Socrates to Wittgenstein: who taught whom, who reacted against whom. The graph is the argument — each dashed edge is a critique, each solid edge a student.",
  snapshot: snap(
    [
      { id: "socrates", name: "Socrates", type: "ancient", domain: "greek", status: "canonical" },
      { id: "plato", name: "Plato", type: "ancient", domain: "greek", status: "canonical" },
      { id: "aristotle", name: "Aristotle", type: "ancient", domain: "greek", status: "canonical" },
      { id: "descartes", name: "Descartes", type: "modern", domain: "rationalist", status: "canonical" },
      { id: "spinoza", name: "Spinoza", type: "modern", domain: "rationalist", status: "canonical" },
      { id: "leibniz", name: "Leibniz", type: "modern", domain: "rationalist", status: "canonical" },
      { id: "locke", name: "Locke", type: "modern", domain: "empiricist", status: "canonical" },
      { id: "hume", name: "Hume", type: "modern", domain: "empiricist", status: "canonical" },
      { id: "kant", name: "Kant", type: "modern", domain: "german", status: "canonical" },
      { id: "hegel", name: "Hegel", type: "continental", domain: "german", status: "canonical" },
      { id: "marx", name: "Marx", type: "continental", domain: "german", status: "canonical" },
      { id: "nietzsche", name: "Nietzsche", type: "continental", domain: "german", status: "canonical" },
      { id: "husserl", name: "Husserl", type: "continental", domain: "phenomenology", status: "canonical" },
      { id: "heidegger", name: "Heidegger", type: "continental", domain: "phenomenology", status: "disputed" },
      { id: "frege", name: "Frege", type: "analytic", domain: "logic", status: "canonical" },
      { id: "russell", name: "Russell", type: "analytic", domain: "logic", status: "canonical" },
      { id: "wittgenstein", name: "Wittgenstein", type: "analytic", domain: "logic", status: "canonical" },
    ],
    [
      { source: "socrates", target: "plato", type: "taught" },
      { source: "plato", target: "aristotle", type: "taught" },
      { source: "aristotle", target: "plato", type: "critiqued" },
      { source: "descartes", target: "aristotle", type: "critiqued" },
      { source: "spinoza", target: "descartes", type: "influenced_by" },
      { source: "leibniz", target: "descartes", type: "influenced_by" },
      { source: "hume", target: "locke", type: "influenced_by" },
      { source: "kant", target: "hume", type: "influenced_by" },
      { source: "kant", target: "leibniz", type: "influenced_by" },
      { source: "hegel", target: "kant", type: "critiqued" },
      { source: "marx", target: "hegel", type: "critiqued" },
      { source: "nietzsche", target: "hegel", type: "critiqued" },
      { source: "husserl", target: "kant", type: "influenced_by" },
      { source: "heidegger", target: "husserl", type: "taught" },
      { source: "frege", target: "kant", type: "influenced_by" },
      { source: "russell", target: "frege", type: "influenced_by" },
      { source: "wittgenstein", target: "russell", type: "taught" },
      { source: "wittgenstein", target: "frege", type: "influenced_by" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      ancient: {
        shape: "roundrectangle",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 60,
        halfHeight: 24,
        labelFont: "Newsreader, serif",
        labelWeight: 600,
      },
      modern: {
        shape: "roundrectangle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 60,
        halfHeight: 24,
        labelFont: "Newsreader, serif",
      },
      continental: {
        shape: "roundrectangle",
        color: "#F3EFE3",
        borderColor: "#7A2C1F",
        halfWidth: 60,
        halfHeight: 24,
        labelColor: "#7A2C1F",
        labelFont: "Newsreader, serif",
      },
      analytic: {
        shape: "square",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 48,
        halfHeight: 24,
        labelFont: "Newsreader, serif",
      },
    },
    edgeTypes: {
      taught: { color: "#1A1714", width: 1.6 },
      influenced_by: { color: "#8A7E68", width: 1.1, style: "solid" },
      critiqued: { color: "#7A2C1F", width: 1.6, style: "dashed" },
    },
  },
};

// ── VI. Circle of fifths ──────────────────────────────────────────────────
const music: Preset = {
  slug: "music",
  folio: "VI",
  title: "Tonality",
  subtitle: "The circle of fifths",
  essay:
    "Twelve keys, each a perfect fifth above the last. The force layout rediscovers the circle on its own — a small proof that the geometry lives in the data, not the diagram.",
  snapshot: snap(
    [
      { id: "C", name: "C", type: "natural", domain: "tonality", status: "neutral" },
      { id: "G", name: "G", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "D", name: "D", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "A", name: "A", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "E", name: "E", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "B", name: "B", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "Fs", name: "F♯", type: "sharp", domain: "tonality", status: "neutral" },
      { id: "Db", name: "D♭", type: "flat", domain: "tonality", status: "neutral" },
      { id: "Ab", name: "A♭", type: "flat", domain: "tonality", status: "neutral" },
      { id: "Eb", name: "E♭", type: "flat", domain: "tonality", status: "neutral" },
      { id: "Bb", name: "B♭", type: "flat", domain: "tonality", status: "neutral" },
      { id: "F", name: "F", type: "flat", domain: "tonality", status: "neutral" },
    ],
    [
      { source: "C", target: "G", type: "fifth" },
      { source: "G", target: "D", type: "fifth" },
      { source: "D", target: "A", type: "fifth" },
      { source: "A", target: "E", type: "fifth" },
      { source: "E", target: "B", type: "fifth" },
      { source: "B", target: "Fs", type: "fifth" },
      { source: "Fs", target: "Db", type: "fifth" },
      { source: "Db", target: "Ab", type: "fifth" },
      { source: "Ab", target: "Eb", type: "fifth" },
      { source: "Eb", target: "Bb", type: "fifth" },
      { source: "Bb", target: "F", type: "fifth" },
      { source: "F", target: "C", type: "fifth" },
      { source: "C", target: "F", type: "fourth" },
      { source: "G", target: "C", type: "fourth" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      natural: {
        shape: "circle",
        color: "#1A1714",
        borderColor: "#1A1714",
        halfWidth: 30,
        halfHeight: 30,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
        labelWeight: 700,
        labelSize: 14,
      },
      sharp: {
        shape: "circle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 28,
        halfHeight: 28,
        labelFont: "Fraunces, serif",
        labelWeight: 600,
        labelSize: 13,
      },
      flat: {
        shape: "circle",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 28,
        halfHeight: 28,
        labelFont: "Fraunces, serif",
        labelWeight: 600,
        labelSize: 13,
      },
    },
    edgeTypes: {
      fifth: { color: "#1A1714", width: 1.4 },
      fourth: { color: "#7A2C1F", width: 1.1, style: "dashed" },
    },
  },
};

// ── VII. Subway ───────────────────────────────────────────────────────────
const subway: Preset = {
  slug: "subway",
  folio: "VII",
  title: "Underground",
  subtitle: "A pocket transit network",
  essay:
    "Stations connected by colored lines. Interchanges are hexagonal — the same shape language as a microservice cache, now meaning a transfer.",
  snapshot: snap(
    [
      { id: "st1", name: "Oakgate", type: "terminal", domain: "north", status: "open" },
      { id: "st2", name: "Harbour", type: "station", domain: "north", status: "open" },
      { id: "st3", name: "Millyard", type: "station", domain: "north", status: "open" },
      { id: "st4", name: "Centre", type: "interchange", domain: "core", status: "open" },
      { id: "st5", name: "Abbey", type: "station", domain: "east", status: "open" },
      { id: "st6", name: "Ironworks", type: "station", domain: "east", status: "open" },
      { id: "st7", name: "Dockside", type: "terminal", domain: "east", status: "open" },
      { id: "st8", name: "Kingsway", type: "interchange", domain: "core", status: "open" },
      { id: "st9", name: "Parkside", type: "station", domain: "west", status: "open" },
      { id: "st10", name: "Elmgrove", type: "station", domain: "west", status: "open" },
      { id: "st11", name: "Westmoor", type: "terminal", domain: "west", status: "closed" },
      { id: "st12", name: "Southbank", type: "station", domain: "south", status: "open" },
      { id: "st13", name: "Heath", type: "terminal", domain: "south", status: "open" },
    ],
    [
      { source: "st1", target: "st2", type: "red" },
      { source: "st2", target: "st3", type: "red" },
      { source: "st3", target: "st4", type: "red" },
      { source: "st4", target: "st8", type: "red" },
      { source: "st8", target: "st12", type: "red" },
      { source: "st12", target: "st13", type: "red" },
      { source: "st5", target: "st4", type: "blue" },
      { source: "st6", target: "st5", type: "blue" },
      { source: "st7", target: "st6", type: "blue" },
      { source: "st4", target: "st9", type: "green" },
      { source: "st9", target: "st10", type: "green" },
      { source: "st10", target: "st11", type: "green" },
      { source: "st8", target: "st4", type: "transfer" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      station: {
        shape: "circle",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 14,
        halfHeight: 14,
        labelFont: "JetBrains Mono, monospace",
        labelSize: 10,
      },
      terminal: {
        shape: "roundrectangle",
        color: "#1A1714",
        borderColor: "#1A1714",
        halfWidth: 46,
        halfHeight: 18,
        labelColor: "#F3EFE3",
        labelFont: "JetBrains Mono, monospace",
        labelWeight: 600,
        labelSize: 10,
      },
      interchange: {
        shape: "hexagon",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        borderWidth: 2,
        halfWidth: 28,
        halfHeight: 26,
        labelFont: "JetBrains Mono, monospace",
        labelSize: 11,
      },
    },
    edgeTypes: {
      red: { color: "#7A2C1F", width: 3.4 },
      blue: { color: "#2C4A7A", width: 3.4 },
      green: { color: "#3E5E3C", width: 3.4 },
      transfer: { color: "#8A7E68", width: 1.4, style: "dotted" },
    },
  },
};

// ── VIII. Recipe ──────────────────────────────────────────────────────────
const recipe: Preset = {
  slug: "recipe",
  folio: "VIII",
  title: "Mise en Place",
  subtitle: "The dependency graph of a loaf of bread",
  essay:
    "Ingredients and techniques arranged as a DAG: each node waits for its inputs. The same shape you'd draw for a build pipeline, now in a kitchen.",
  snapshot: snap(
    [
      { id: "flour", name: "Flour", type: "ingredient", domain: "pantry", status: "raw" },
      { id: "water", name: "Water", type: "ingredient", domain: "pantry", status: "raw" },
      { id: "salt", name: "Salt", type: "ingredient", domain: "pantry", status: "raw" },
      { id: "starter", name: "Starter", type: "ingredient", domain: "pantry", status: "living" },
      { id: "mix", name: "Mix & Rest", type: "technique", domain: "process", status: "step" },
      { id: "dough", name: "Dough", type: "intermediate", domain: "process", status: "resting" },
      { id: "fold", name: "Stretch & Fold", type: "technique", domain: "process", status: "step" },
      { id: "bulk", name: "Bulk Ferment", type: "technique", domain: "process", status: "step" },
      { id: "shape", name: "Shape", type: "technique", domain: "process", status: "step" },
      { id: "proof", name: "Cold Proof", type: "technique", domain: "process", status: "step" },
      { id: "score", name: "Score", type: "technique", domain: "process", status: "step" },
      { id: "bake", name: "Bake", type: "technique", domain: "process", status: "step" },
      { id: "bread", name: "Sourdough", type: "output", domain: "yield", status: "ready" },
    ],
    [
      { source: "flour", target: "mix", type: "feeds" },
      { source: "water", target: "mix", type: "feeds" },
      { source: "salt", target: "mix", type: "feeds" },
      { source: "starter", target: "mix", type: "feeds" },
      { source: "mix", target: "dough", type: "yields" },
      { source: "dough", target: "fold", type: "needs" },
      { source: "fold", target: "bulk", type: "needs" },
      { source: "bulk", target: "shape", type: "needs" },
      { source: "shape", target: "proof", type: "needs" },
      { source: "proof", target: "score", type: "needs" },
      { source: "score", target: "bake", type: "needs" },
      { source: "bake", target: "bread", type: "yields" },
    ],
  ),
  overrides: {
    canvasBg: "#F3EFE3",
    gridLineColor: "#E4DECB",
    labelHalo: "#F3EFE3",
    selectionBorder: "#7A2C1F",
    nodeTypes: {
      ingredient: {
        shape: "circle",
        color: "#EAE1CC",
        borderColor: "#1A1714",
        halfWidth: 36,
        halfHeight: 26,
        labelFont: "Fraunces, serif",
      },
      technique: {
        shape: "square",
        color: "#F3EFE3",
        borderColor: "#1A1714",
        halfWidth: 58,
        halfHeight: 22,
        labelFont: "JetBrains Mono, monospace",
        labelSize: 11,
      },
      intermediate: {
        shape: "roundrectangle",
        color: "#F3EFE3",
        borderColor: "#8A7E68",
        halfWidth: 52,
        halfHeight: 22,
        labelFont: "Fraunces, serif",
      },
      output: {
        shape: "barrel",
        color: "#7A2C1F",
        borderColor: "#7A2C1F",
        halfWidth: 56,
        halfHeight: 28,
        labelColor: "#F3EFE3",
        labelFont: "Fraunces, serif",
        labelWeight: 600,
      },
    },
    edgeTypes: {
      feeds: { color: "#8A7E68", width: 1.2, style: "dashed" },
      needs: { color: "#1A1714", width: 1.5 },
      yields: { color: "#7A2C1F", width: 1.9 },
    },
  },
};

export const PRESETS: readonly Preset[] = [
  architecture,
  mythology,
  molecules,
  hamlet,
  philosophy,
  music,
  subway,
  recipe,
] as const;

export function presetBySlug(slug: string): Preset {
  return PRESETS.find((p) => p.slug === slug) ?? PRESETS[0];
}
